version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "priyankas-good-greens"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1fh54iz3nan0g"
s3_prefix = "priyankas-good-greens"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
